<?php
require_once "connection.php";
require_once "fpdf/fpdf.php";

$eid = $_GET['pdfid'];
$result = "SELECT * FROM fptbl WHERE id='$eid'";
$sql = $conn->query($result);

$pdf = new FPDF();
$pdf->AddPage();
$pdf->SetFont('Arial', '', 12);
$pdf->Cell(190, 10, 'Southern Leyte State University - College of Teacher Education', 0, 0, 'C');
$pdf->Ln();
$pdf->SetFont('Arial', '', 12);
$pdf->Cell(190, 10, 'San Isidro, Tomas Oppus, Southern Leyte', 0, 0, 'C');
$pdf->Ln();
$pdf->SetFont('Arial', '', 12);
$pdf->Cell(190, 10, 'Bachelor of Science in Information Technology', 0, 0, 'C');
$pdf->Ln();
$pdf->SetFont('Arial', 'B', 20);
$pdf->Cell(190, 10, 'Computer Society', 0, 0, 'C');
$pdf->Image('slsu.png', 10, 8, 27);
$pdf->Image('comsoc.jpeg', 170, 8, 30);
$pdf->Ln();
$pdf->Ln();
$pdf->SetFont('Arial', 'B', 12);
while($row = $sql->fetch_object()) {
    $studid=$row->studid;
    $fullname=$row->fullname;
    $birthdate=$row->birthdate;
    $age=$row->age;
    $mobilenumber=$row->mobilenumber;
    $address=$row->address;
    $choice=$row->choice;
    $nationality=$row->nationality;
    $religion=$row->religion;
    $civilstatus=$row->civilstatus;
    $email=$row->email;
    $major=$row->major;
    $yearlevel=$row->yearlevel;
    $section=$row->section;
    $cpname=$row->cpname;
    $cpnumber=$row->cpnumber;

    $pdf->Cell(40, 10, 'Student ID: ', 0, 0, 'L');
    $pdf->Cell(170,10, $studid, 0, 0, 'L');
    $pdf->Ln();
    $pdf->Cell(40, 10, 'Fullname: ', 0, 0, 'L');
    $pdf->Cell(170,10, $fullname, 0, 0, 'L');
    $pdf->Ln();
    $pdf->Cell(40, 10, 'Birthdate: ', 0, 0, 'L');
    $pdf->Cell(170,10, $birthdate, 0, 0, 'L');
    $pdf->Ln();
    $pdf->Cell(40, 10, 'Age: ', 0, 0, 'L');
    $pdf->Cell(170,10, $age, 0, 0, 'L');
    $pdf->Ln();
    $pdf->Cell(40, 10, 'Mobile Number: ', 0, 0, 'L');
    $pdf->Cell(170,10, $mobilenumber, 0, 0, 'L');
    $pdf->Ln();
    $pdf->Cell(40, 10, 'Address: ', 0, 0, 'L');
    $pdf->Cell(170,10, $address, 0, 0, 'L');
    $pdf->Ln();
    $pdf->Cell(40, 10, 'Sex: ', 0, 0, 'L');
    $pdf->Cell(170,10, $choice, 0, 0, 'L');
    $pdf->Ln();
    $pdf->Cell(40, 10, 'Nationality: ', 0, 0, 'L');
    $pdf->Cell(170,10, $nationality, 0, 0, 'L');
    $pdf->Ln();
    $pdf->Cell(40, 10, 'Religion: ', 0, 0, 'L');
    $pdf->Cell(170,10, $religion, 0, 0, 'L');
    $pdf->Ln();
    $pdf->Cell(40, 10, 'Civil Status: ', 0, 0, 'L');
    $pdf->Cell(170,10, $civilstatus, 0, 0, 'L');
    $pdf->Ln();
    $pdf->Cell(40, 10, 'Email Address: ', 0, 0, 'L');
    $pdf->Cell(170,10, $email, 0, 0, 'L');
    $pdf->Ln();
    $pdf->Cell(40, 10, 'Major: ', 0, 0, 'L');
    $pdf->Cell(170,10, $major, 0, 0, 'L');
    $pdf->Ln();
    $pdf->Cell(40, 10, 'Year Level: ', 0, 0, 'L');
    $pdf->Cell(170,10, $yearlevel, 0, 0, 'L');
    $pdf->Ln();
    $pdf->Cell(40, 10, 'Section: ', 0, 0, 'L');
    $pdf->Cell(170,10, $section, 0, 0, 'L');
    $pdf->Ln();
    $pdf->Ln();
    $pdf->Cell(40, 10, 'Incase of Emergency ', 0, 0, 'L');
    $pdf->Ln();
    $pdf->Cell(40, 10, 'Contact Person: ', 0, 0, 'L');
    $pdf->Cell(170,10, $cpname, 0, 0, 'L');
    $pdf->Ln();
    $pdf->Cell(40, 10, 'Contact Number: ', 0, 0, 'L');
    $pdf->Cell(170,10, $cpnumber, 0, 0, 'L');
    $pdf->Ln();
}

$pdf->Output();
?>